name: Docs

on:
  pull_request:

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1
        with:
          git-push: true
